config/routes.rb
Rails.application.routes.draw do
  resources :user_profiles
  devise_for :users
  resources :photos
  get 'albums/index'

  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :shares
  has_many :photos
  belongs_to :user
  accepts_nested_attributes_for :shares
  accepts_nested_attributes_for :user
  attr_accessor :share_email
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album

  has_attached_file :img, styles: {
      thumb: '100x100>',
      square: '200x200#',
      medium: '300x300>'
  }
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :album
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :shares
  has_one :user_profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :check_is_shared, only: [:edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.where(user_id: current_user.id)
    @shares = Share.where(user_id: current_user.id)
    @shares.each {
      |share| @albums += Album.where(id: share.album.id)
    }
  end

  # GET /albums/1
  # GET /albums/1.json
  def show

  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      user = User.find_by_email(params[:share_email])

      if user != nil
        # Überprüfen, ob Album noch nicht geteilt wurde mit dem User
        if not @album.shares.any? {|share| share.user_id == user.id}
          share = Share.new
          share.album = @album
          share.user = user
          @album.shares << share
        end

      end

      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.includes(:photos, :shares).find(params[:id])
    end

  def check_is_shared
    puts @album.user_id
    if @album.user_id != current_user.id
      respond_to do |format|
        format.html { redirect_to albums_url, notice: 'Album gehört nicht dir.' }
        format.json { head :no_content }
      end
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :description, :share_email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @photo.album_id = params[:album_id]
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    if @photo.update(photo_params)
      redirect_to album_url(@photo.album_id)
    else
      render :edit
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    album_id = @photo.album_id
    @photo.destroy
    redirect_to album_url(album_id)
  end

  protected

  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  def set_photos
    @photos = @album.photos.page(params[:page])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_params
    params.require(:photo).permit(:description, :album_id, :img)
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:edit, :update]

  # GET /user_profiles/1/edit
  def edit
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to edit_user_profile_path, notice: 'Daten erfolgreich aktualisiert.' }
        format.json { render :edit, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      UserProfile.find_or_initialize_by(user: current_user) do |userprofile|
        @user_profile = userprofile
        @user_profile.save
      end
      if @user_profile == nil
        @user_profile = UserProfile.find_by_user_id(current_user.id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:firstname, :lastname, :street, :city, :zipcode)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :title, id: :album_title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :Beschreibung %>
    <%= form.text_field :description, id: :album_description, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <span><b>Teilen mit</b></span> <input type="text" class="form-control" placeholder="E-Mail" name="share_email">
  </div>

  <br>
  <button type="submit" class="btn btn-primary">Speichern</button>
<% end %>

app/views/albums/edit.html.erb
<h1>Album ändern</h1>
<p>
  <%= link_to 'Zurück zum Album', @album, :class => "btn btn-default" %>
</p>
<%= render 'form', album: @album %>

app/views/albums/index.html.erb
<h1>Alben</h1>

<% if @albums.length > 0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Beschreibung</th>
      <th>Aktionen</th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.description %></td>
        <td>
          <%= link_to 'Anzeigen', album, :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Ändern', edit_album_path(album), :class => "btn btn-warning btn-sm" %>
          <%= link_to 'Löschen', album, method: :delete, data: { confirm: 'Album wirklich löschen?' }, :class => "btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Lege jetzt dein erstes Album an!</p>
<% end %>

<br>

<%= link_to 'Neues Album erstellen', new_album_path, :class => "btn btn-primary" %>

app/views/albums/new.html.erb
<h1>Neues Album</h1>
<p><%= link_to 'Zurück zur Alben-Liste', albums_path, :class => "btn btn-default btn-sm" %></p>
<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<div class="jumbotron">
<h2><%= @album.title %></h2>
<p><%= @album.description %></p>
<% if @album.user_id == current_user.id %>
  <% if @album.shares.count > 0 %>
    <p>Geteilt mit:
      <% @album.shares.each do |share| %>
        <span><%= share.user.email %> </span>
      <% end %>
    </p>
  <% else %>
    <p>Album ist mit keinem geteilt!</p>
  <% end %>
<% end %>
<%= link_to 'Zurück zur Alben-Liste', albums_path, :class => "btn btn-default btn-sm" %>
<%= link_to 'Ändern', edit_album_path(@album), :class => "btn btn-primary btn-sm" %>
</div>
<h3>Fotos</h3>
<p>
  <%= link_to 'Foto hinzufügen', new_photo_path(:album_id => @album.id), :class => "btn btn-success" %>
</p>
<div class="row">
  <% @album.photos.each do |photo| %>
  <div class="col-xs-12 col-sm-4 col-md-3">
    <div class="thumbnail">
      <img src="<%= photo.img.url(:square) %>" alt="">
      <div class="caption">
        <p><%= photo.description %></p>
        <%= link_to ' ', photo, :class => "btn btn-primary btn-sm glyphicon glyphicon-eye-open" %>
        <%= link_to ' ', edit_photo_path(photo), :class => "btn btn-warning btn-sm glyphicon glyphicon-pencil" %>
        <%= link_to ' ', photo, method: :delete, data: { confirm: 'Foto wirklich löschen?' }, :class => "btn btn-danger btn-sm glyphicon glyphicon-trash" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPhotoGallery</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Deine Fotoalben</a>
      </div>
      <div class="collapse navbar-collapse">
        <!--<ul class="nav navbar-nav navbar-right">
          <li><a href="#">Sign In</a></li>
          <li><a href="#">Sign Up</a></li>
        </ul>-->
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
              <strong><%= current_user.email %></strong> |
              <%= link_to 'Persönliche Daten', edit_user_profile_path(current_user.id), :class => 'navbar-link' %> |
              <%= link_to 'Dein Konto', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Abmelden", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
              <%= link_to "Registrieren", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Anmelden", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </div>
  </nav>

  <br><br><br>
  <div class="container">
    <% if notice %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
    <% end %>
    <% if alert %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
    <% end %>
    <%= yield %>
  </div>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true , multipart: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Beschreibung %>
    <%= form.text_field :description, id: :photo_description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :Bilddatei %>
    <%= form.file_field :img %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :file_url %>
    <%= form.text_field :file_url, id: :photo_file_url, class: 'form-control' %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :file_size %>
    <%= form.text_field :file_size, id: :photo_file_size %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :file_type %>
    <%= form.text_field :file_type, id: :photo_file_type %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :album_id %>
    <%= form.text_field :album_id, id: :photo_album_id %>
  </div>

  <br>
  <button type="submit" class="btn btn-primary">Speichern</button>
<% end %>

app/views/photos/edit.html.erb
<h1>Foto ändern</h1>
<p>
  <%= link_to 'Zurück zum Album', @photo.album, :class => "btn btn-default" %>
</p>
<%= render 'form', photo: @photo %>

app/views/photos/new.html.erb
<h2>Foto hinzufügen</h2>
<p>
  <%= link_to 'Zurück zum Album', @photo.album, :class => "btn btn-default" %>
</p>

<%= render 'form', photo: @photo %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Zurück zum Album', @photo.album, :class => "btn btn-default" %>
</p>

<p>
  <strong>Beschreibung:</strong>
  <%= @photo.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @photo.img.url %>
</p>

<p>
  <strong>Album:</strong>
  <%= @photo.album.description %>
</p>

<img src="<%= @photo.img.url %>" alt="">

app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="input_firstname">Vorname:</label>
    <%= form.text_field :firstname, class: "form-control", id: "input_firstname" %>
  </div>

  <div class="field">
    <label for="input_lastname">Nachname:</label>
    <%= form.text_field :lastname, class: "form-control", id: "input_lastname" %>
  </div>

  <div class="field">
    <label for="input_street">Strasse:</label>
    <%= form.text_field :street, class: "form-control", id: "input_fstreet" %>
  </div>

  <div class="field">
    <label for="input_city">Ort:</label>
    <%= form.text_field :city, class: "form-control", id: "input_city" %>
  </div>

  <div class="field">
    <label for="input_zipcode">PLZ:</label>
    <%= form.text_field :zipcode, class: "form-control", id: "input_zipcode" %>
  </div>

  <br>
  <button type="submit" class="btn btn-primary">Speichern</button>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Persönliche Daten</h1>

<%= render 'form', user_profile: @user_profile %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Rails Photo Gallery</h1>
<%= link_to 'Alben-Liste', albums_path %>